### ISSUE TITLE
Using find-tag with evil-jumper

### ISSUE THREAD

**Issue by duff** [bling/evil-jumper#13]
Hi,

When I use the `find-tag` function to jump to the definition of a method or variable, it brings me to the appropriate file / location where the function is defined.  But then if I attempt to use `C-o` to jump back to where I was, that doesn't seem to bring me back to where I initially used the `find-tag` function.

I was wondering if there might be a setting to help with it or if folks are using some other function rather than `find-tag`.

I thought I'd ask here before digging in too far to see if I might implement a fix.  Thanks!!

**Comment by bling** [comment]
hmmm, looks like the `switch-to-buffer` advice is setting the jump to the `TAGS` file, not the original file.

**Comment by duff** [comment]
NICE!  Thanks!!!
