### ISSUE TITLE
Suggestion: use markers instead of point

### ISSUE THREAD

**Issue by bmag** [bling/evil-jumper#14]
First of all, thank you for making this package. Secondly, I've encountered an irritating behaviour when using your package, explained below.

If I jump to some location in the current buffer, make some changes, and then jump back, sometimes the jump back "misses"  by several characters. To reproduce:
1. from the end of the buffer, jump to the beginning of the buffer
2. type "foo" (in insert state)
3. jump back with `evil-jumper/backward`
Expected result: point is now at end of buffer
Actual result: point is 3 characters before the end of the buffer.

Using markers should fix this problem, since markers keep track of such changes. I'm guessing the function `point-marker` will be helpful.

**Comment by bling** [comment]
thanks.
