### ISSUE TITLE
C-o after repeated evil-find-char behaves differently from vim

### ISSUE THREAD

**Issue by sooheon** [bling/evil-jumper#15]
This diagram from vim-sneak shows the general idea that after repeating a search motion repeatedly with `;`, you can press `C-o` once to jump back to before the initial search. This doesn't work with evil-jumper. Is this a reconcilable difference?

<a href="http://imgur.com/Jke0mIJ" title="Click to see a short demo"><img src="https://raw.github.com/justinmk/vim-sneak/fluff/assets/readme_diagram.png"></a>

**Comment by bling** [comment]
i'm not following.  can you give a more concrete example?  also, all evil-jumper does is extend evil-mode's jumps to span across files.  if what you're after doesn't work in the same buffer then the issue would be lack of support in evil-mode itself.

**Comment by sooheon** [comment]
Hm, you're right it's an issue for evil itself. Just in case you have any ideas:

1. Search for a letter with `f letter`
2. Repeat the search with `;`
3. `C-o` takes you back to before the initial `f` search in vim. In evil, it takes you back step by step as if you're pressing `,`
