### ISSUE TITLE
evil-jumper--write-file needs password for tramp items

### ISSUE THREAD

**Issue by Szunti** [bling/evil-jumper#16]
Used tramp with sudo. Quit emacs. Started a new emacs.
And (evil-jumper--write-file) wants the sudo password. Especially bad because save-buffers-kill-emacs
is adviced to call it. So from now on I always have to give password to quit emacs.

**Comment by bling** [comment]
so the jumps file ended up with root permissions?

**Comment by Szunti** [comment]
No. It just checks if the file still exists when writing the list to the jump file. And it need root permissions for that.

**Comment by bling** [comment]
i'm not too familiar with tramp, but if could give me a simple example that reproduces this i'll see if there's something can be done code-wise.

but since this only started happening after you used tramp with sudo leads me to believe that something changed with your permissions.  perhaps you can try deleting the file and see if the problem still persists?

**Comment by Szunti** [comment]
Sorry, my comment was not clear enough, I meant line 146. where evil-jumper--write-file checks if the jump's target file still exists. (not the jump-list file).
Running

  (file-exists-p "/sudo:root@localhost:/etc/passwd")

for example asks for password. Generally it has to because you could need root permissions even to check that the file exists. It's more understandable with ssh connections.

**Comment by bling** [comment]
is it safe to assume that if i find anything like `\/.*:` that it would be a remote file?  then we can have the check only apply to local files.

**Comment by Szunti** [comment]
I think it should be `/[^/]*:`  to restrict only the files in the root filesystem. There are files under my /sys/
with : in them for example.

**Comment by Szunti** [comment]
Just found file-remote-p. I think that is exactly what you need.

**Comment by bling** [comment]
cool, can you try redefining the function to the following to see if it fixes it for you?  there's a PR to replace saving with `savehist`, but until that happens this should at least solve this problem for you.

```
(defun evil-jumper--write-file ()
  "Saves the current contents of the jump list to a persisted file."
  (with-temp-file evil-jumper-file
    (let ((jumps (evil-jumper--get-window-jump-list)))
      (dolist (jump jumps)
        (let* ((mark (car jump))
               (pos (if (markerp mark)
                        (marker-position mark)
                      mark))
               (file-name (cadr jump)))
          (when (and (file-exists-p file-name) (not (file-remote-p file-name)) pos)
            (insert (format "%d" pos))
            (insert " ")
            (insert file-name)
            (insert "\n")))))))
```

**Comment by Szunti** [comment]
You should put file-remote-p first I think.

Somehow I couldn't trigger emacs to ask for the sudo password again after giving it. So maybe it doesn't matter.
