### ISSUE TITLE
evil-jumper doesn't work inside of "tags" directory

### ISSUE THREAD

**Issue by bmag** [bling/evil-jumper#17]
I'm working on several files in a directory called "tags", and evil-jumper doesn't record any jumps I make inside those files. Removing "TAGS" from `evil-jumper-ignored-file-patterns` solved the problem for me, but of course that is a bad solution.

**Comment by bmag** [comment]
Changing `evil-jumper-ignored-file-patterns` from `("COMMIT_EDITMSG" "TAGS")` to `("COMMIT_EDITMSG" "TAGS$")` solves it for me. Maybe that should be the default?

**Comment by bling** [comment]
yes, that would make sense.  and while you're at it you can add a $ to commit_editmsg as well.  wanna file a PR?

**Comment by bmag** [comment]
See PR at #18

**Comment by bling** [comment]
#18 merged.  thanks!
